# spring 配置
spring:
  application:
    name: OGT_System
  # 请求设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  # redis数据源
  redis:
    # 基础设置
    database: 0
    host: 150.158.98.146
    port: 6379
    password: ogt88zxcvbnm88
    connect-timeout: 3000
    # 线程设置
    lettuce:
      pool:
        max-active: 8                             # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1                              # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8                               # 连接池中的最大空闲连接 默认 8
        min-idle: 0                               # 连接池中的最小空闲连接 默认 0
  # Mysql数据源
  datasource:
    url: jdbc:mysql://150.158.98.146:3306/OGT_System?serverTimezone=UTC
    username: root
    password: 88.Zxcvbnm88
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
    dbcp2:
      min-idle: 5                                 # 数据库连接池的最小维持连接数
      initial-size: 5                             # 初始化连接数
      max-total: 5                                # 最大连接数
      max-wait-millis: 150                        # 等待连接获取的最大超时时间


# spring-web-server 配置
server:
  port: 8888


# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml    # mapper映射文件位置
  type-aliases-package: entity    # 实体类所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句


# ali oss
aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-beijing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tFKyusizWFTFMtGw1Fn
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: yGdTWG1VYy1Jz9gRGAfCMJSaQ0ZKdX
    # oss的存储空间
    bucketName: ogt-test-image-oss-ali-01
    # 上传文件大小(M)
    maxSize: 200
    # 上传文件夹路径前缀
    dir:
      prefix: ogt/images/


# baidu cloud
baiduyun:
  tokenUrl: https://aip.baidubce.com/oauth/2.0/token
  textReview:
    apiKey: yt1r87bwCDtpoxaFnSHAqn2y
    secretKey: KcfZmcVhsBPCVdWT3fufGQVCZdE1sw4N
    url: https://aip.baidubce.com/rest/2.0/solution/v1/text_censor/v2/user_defined
